# City Murder Rates
# Authors: Muhammad Salim and Jovani Munoz


import turtle
import random
import matplotlib.pyplot as plt

phiscreen = turtle.getscreen()
choicescreen = turtle.getscreen()
nycscreen = turtle.getscreen()
chiscreen = turtle.getscreen()
detscreen = turtle.getscreen()


def opening_screen():
    openingscreen = turtle.getscreen()
    opening_writing = turtle.Turtle()
    opening_writing.hideturtle()
    openingscreen.bgcolor("black")
    opening_writing.penup()
    opening_writing.goto(0,200)
    opening_writing.pencolor("white")
    opening_writing.pendown()
    opening_writing.write("Crime Rates in US Cities", False, align = "center", font = ('times new roman',40))
    crime_image = turtle.Turtle()
    crime_image.hideturtle()
    turtle.addshape("crime.gif")
    crime_image.shape("crime.gif")
    crime_image.penup()
    crime_image.goto(0,30)
    crime_image.showturtle()
    opening_question = input("Would you like to begin? (Yes or No) : ").lower()
    while opening_question != "no" and opening_question != "yes":
       print("Sorry, invalid input!")
       print("Try again!")
       opening_question = input("Would you like to begin? (Yes or No) : ").lower()
    if opening_question == "no":
        openingscreen.clearscreen()
        end_screen()
    elif opening_question == "yes":
        openingscreen.clearscreen()
        citychoice_screen()


def citychoice_screen():
    choicescreen.bgcolor("black")
    instruction_turtle = turtle.Turtle()
    instruction_turtle.hideturtle()
    instruction_turtle.penup()
    instruction_turtle.goto(0,225)
    instruction_turtle.pencolor("white")
    instruction_turtle.pendown()
    instruction_turtle.write("Click City of Choice", False, align = "center", font = ('times new roman',25))
    bean_turtle = turtle.Turtle()
    bean_turtle.penup()
    turtle.addshape("thebean (3).gif")
    bean_turtle.shape("thebean (3).gif")
    bean_turtle.goto(-150,85)
    timessquare_turtle = turtle.Turtle()
    timessquare_turtle.penup()
    turtle.addshape("timesquare.gif")
    timessquare_turtle.shape("timesquare.gif")
    timessquare_turtle.goto(150,85)
    detriot_turtle = turtle.Turtle()
    detriot_turtle.penup()
    turtle.addshape("detroit.gif")
    detriot_turtle.shape("detroit.gif")
    detriot_turtle.goto(150,-125)
    rocky_turtle = turtle.Turtle()
    rocky_turtle.penup()
    turtle.addshape("rocky.gif")
    rocky_turtle.shape("rocky.gif")
    rocky_turtle.goto(-150,-125)
    chitext_turtle = turtle.Turtle()
    chitext_turtle.hideturtle()
    chitext_turtle.penup()
    chitext_turtle.goto(-150,175)
    chitext_turtle.pencolor("white")
    chitext_turtle.pendown()
    chitext_turtle.write("Chicago", False, align = "center", font = ('Arial',15))
    nyctext_turtle = turtle.Turtle()
    nyctext_turtle.hideturtle()
    nyctext_turtle.penup()
    nyctext_turtle.goto(150,175)
    nyctext_turtle.pencolor("white")
    nyctext_turtle.pendown()
    nyctext_turtle.write("New York", False, align = "center", font = ('Arial',15))
    dettext_turtle = turtle.Turtle()
    dettext_turtle.hideturtle()
    dettext_turtle.penup()
    dettext_turtle.goto(150,-25)
    dettext_turtle.pencolor("white")
    dettext_turtle.pendown()
    dettext_turtle.write("Detroit", False, align = "center", font = ('Arial',15))
    phitext_turtle = turtle.Turtle()
    phitext_turtle.hideturtle()
    phitext_turtle.penup()
    phitext_turtle.goto(-150,-25)
    phitext_turtle.pencolor("white")
    phitext_turtle.pendown()
    phitext_turtle.write("Philadelphia", False, align = "center", font = ('Arial',15))
    timessquare_turtle.onclick(nyc_screen)
    detriot_turtle.onclick(det_screen)
    bean_turtle.onclick(chi_screen)
    rocky_turtle.onclick(phi_screen)


def read_data(filename):
    file = open(filename)
    data = file.readlines()
    clean_data(data)
    return data

def clean_data(list):
  for i in range(len(list)):
    if list[i] == "<1\n" or list[i] == "<1":
      list[i] = 0
    else:
      list[i] = int(list[i])

def nyc_graph(x,y):
    nyc = read_data("nyc.txt")
    plt.plot(nyc,'b--')
    plt.title("Murders in New York City")
    plt.ylabel("Murders")
    plt.xlabel("Years After 1999")
    # plt.savefig("nyc.png") #graph was created then changed to .gif and then a turtle
    plt.show()

def chi_graph(x,y):
    chi = read_data("chi.txt")
    plt.plot(chi,'b--')
    plt.title("Murders in Chicago")
    plt.ylabel("Murders")
    plt.xlabel("Years After 1999")
    # plt.savefig("chi.png") #graph was created then changed to .gif and then a turtle
    plt.show()

def det_graph(x,y):
    det = read_data("det.txt")
    plt.plot(det,'b--')
    plt.title("Murders in Detroit")
    plt.ylabel("Murders")
    plt.xlabel("Years After 1999")
    # plt.savefig("det.png") #graph was created then changed to .gif and then a turtle
    plt.show()

def phi_graph(x,y):
    phi = read_data("phi.txt")
    plt.plot(phi,'b--')
    plt.title("Murders in Philadelphia")
    plt.ylabel("Murders")
    plt.xlabel("Years After 1999")
    # plt.savefig("phi.png") #graph was created then changed to .gif and then a turtle
    plt.show()

def all_graph(): # creates graph of all cities
    phi = read_data("det.txt")
    nyc = read_data("nyc.txt")
    chi = read_data("chi.txt")
    det = read_data("det.txt")
    plt.plot(phi,'b--')
    plt.plot(nyc,'g*:')
    plt.plot(chi,'cd:')
    plt.plot(det,'C1-.')
    plt.title("Murders in Different US Cities")
    plt.ylabel("Murders")
    plt.xlabel("Years After 1999")
    plt.legend(["Philadelphia","New York", "Chicago","Detriot"])
    plt.show()




def end_screen():
    endscreen = turtle.getscreen()
    end_writing = turtle.Turtle()
    end_writing.hideturtle()
    endscreen.bgcolor("black")
    end_writing.penup()
    end_writing.goto(0,200)
    end_writing.pencolor("white")
    end_writing.pendown()
    end_writing.write("Thank You", False, align = "center", font = ('Arial',40))
    end_writing.penup()
    end_writing.goto(0,125)
    end_writing.pendown()
    end_writing.write("For Using The App!", False, align = "center", font = ('Arial',40))
    endcities_image = turtle.Turtle()
    endcities_image.hideturtle()
    turtle.addshape("endscreen3.gif")
    endcities_image.shape("endscreen3.gif")
    endcities_image.penup()
    endcities_image.goto(0,-50)
    endcities_image.showturtle()

def nyc_screen(x,y):
    choicescreen.clearscreen()
    nycscreen.bgcolor('black')
    nyc_graph = turtle.Turtle()
    nyc_graph.hideturtle()
    turtle.addshape("nyc.gif")
    nyc_graph.shape("nyc.gif")
    nyc_graph.penup()
    nyc_graph.goto(0,100)
    nyc_graph.showturtle()
    cancel_turtle = turtle.Turtle()
    cancel_turtle.hideturtle()
    turtle.addshape('cancel.gif')
    cancel_turtle.shape('cancel.gif')
    cancel_turtle.penup()
    cancel_turtle.goto(175,-175)
    cancel_turtle.showturtle()
    reset_turtle = turtle.Turtle()
    reset_turtle.hideturtle()
    turtle.addshape('reset.gif')
    reset_turtle.shape('reset.gif')
    reset_turtle.penup()
    reset_turtle.goto(-175, -175)
    reset_turtle.showturtle()
    allcity_turtle = turtle.Turtle()
    allcity_turtle.hideturtle()
    turtle.addshape('allcities.gif')
    allcity_turtle.shape('allcities.gif')
    allcity_turtle.penup()
    allcity_turtle.goto(0, -175)
    allcity_turtle.showturtle()
    reset_turtle.onclick(reset_citychoice)
    allcity_turtle.onclick(all_screen)
    cancel_turtle.onclick(end_app)

def chi_screen(x,y):
    choicescreen.clearscreen()
    chiscreen.bgcolor('black')
    chi_graph = turtle.Turtle()
    chi_graph.hideturtle()
    turtle.addshape("chi.gif")
    chi_graph.shape("chi.gif")
    chi_graph.penup()
    chi_graph.goto(0,100)
    chi_graph.showturtle()
    cancel_turtle = turtle.Turtle()
    cancel_turtle.hideturtle()
    turtle.addshape('cancel.gif')
    cancel_turtle.shape('cancel.gif')
    cancel_turtle.penup()
    cancel_turtle.goto(175,-175)
    cancel_turtle.showturtle()
    reset_turtle = turtle.Turtle()
    reset_turtle.hideturtle()
    turtle.addshape('reset.gif')
    reset_turtle.shape('reset.gif')
    reset_turtle.penup()
    reset_turtle.goto(-175, -175)
    reset_turtle.showturtle()
    allcity_turtle = turtle.Turtle()
    allcity_turtle.hideturtle()
    turtle.addshape('allcities.gif')
    allcity_turtle.shape('allcities.gif')
    allcity_turtle.penup()
    allcity_turtle.goto(0, -175)
    allcity_turtle.showturtle()
    reset_turtle.onclick(reset_citychoice)
    allcity_turtle.onclick(all_screen)
    cancel_turtle.onclick(end_app)

def det_screen(x,y):
    choicescreen.clearscreen()
    detscreen = turtle.getscreen()
    detscreen.bgcolor('black')
    det_graph = turtle.Turtle()
    det_graph.hideturtle()
    turtle.addshape("det.gif")
    det_graph.shape("det.gif")
    det_graph.penup()
    det_graph.goto(0,100)
    det_graph.showturtle()
    cancel_turtle = turtle.Turtle()
    cancel_turtle.hideturtle()
    turtle.addshape('cancel.gif')
    cancel_turtle.shape('cancel.gif')
    cancel_turtle.penup()
    cancel_turtle.goto(175,-175)
    cancel_turtle.showturtle()
    reset_turtle = turtle.Turtle()
    reset_turtle.hideturtle()
    turtle.addshape('reset.gif')
    reset_turtle.shape('reset.gif')
    reset_turtle.penup()
    reset_turtle.goto(-175, -175)
    reset_turtle.showturtle()
    allcity_turtle = turtle.Turtle()
    allcity_turtle.hideturtle()
    turtle.addshape('allcities.gif')
    allcity_turtle.shape('allcities.gif')
    allcity_turtle.penup()
    allcity_turtle.goto(0, -175)
    allcity_turtle.showturtle()
    reset_turtle.onclick(reset_citychoice)
    allcity_turtle.onclick(all_screen)
    cancel_turtle.onclick(end_app)

def phi_screen(x,y):
    choicescreen.clearscreen()
    phiscreen.bgcolor('black')
    phi_graph = turtle.Turtle()
    phi_graph.hideturtle()
    turtle.addshape("phi.gif")
    phi_graph.shape("phi.gif")
    phi_graph.penup()
    phi_graph.goto(0,100)
    phi_graph.showturtle()
    cancel_turtle = turtle.Turtle()
    cancel_turtle.hideturtle()
    turtle.addshape('cancel.gif')
    cancel_turtle.shape('cancel.gif')
    cancel_turtle.penup()
    cancel_turtle.goto(175,-175)
    cancel_turtle.showturtle()
    reset_turtle = turtle.Turtle()
    reset_turtle.hideturtle()
    turtle.addshape('reset.gif')
    reset_turtle.shape('reset.gif')
    reset_turtle.penup()
    reset_turtle.goto(-175, -175)
    reset_turtle.showturtle()
    allcity_turtle = turtle.Turtle()
    allcity_turtle.hideturtle()
    turtle.addshape('allcities.gif')
    allcity_turtle.shape('allcities.gif')
    allcity_turtle.penup()
    allcity_turtle.goto(0, -175)
    allcity_turtle.showturtle()
    reset_turtle.onclick(reset_citychoice)
    allcity_turtle.onclick(all_screen)
    cancel_turtle.onclick(end_app)

def all_screen(x,y):
    turtle.clearscreen()
    allscreen = turtle.getscreen()
    allscreen.bgcolor('black')
    all_graph = turtle.Turtle()
    all_graph.hideturtle()
    turtle.addshape("all.gif")
    all_graph.shape("all.gif")
    all_graph.penup()
    all_graph.goto(0,100)
    all_graph.showturtle()
    cancel_turtle = turtle.Turtle()
    cancel_turtle.hideturtle()
    turtle.addshape('cancel.gif')
    cancel_turtle.shape('cancel.gif')
    cancel_turtle.penup()
    cancel_turtle.goto(100,-175)
    cancel_turtle.showturtle()
    reset_turtle = turtle.Turtle()
    reset_turtle.hideturtle()
    turtle.addshape('reset.gif')
    reset_turtle.shape('reset.gif')
    reset_turtle.penup()
    reset_turtle.goto(-100, -175)
    reset_turtle.showturtle()
    reset_turtle.onclick(reset_citychoice)
    cancel_turtle.onclick(end_app)



def reset_citychoice(x,y): #paramters added for onclick function
    turtle.clearscreen()
    citychoice_screen()

def end_app(x,y): #paramters added for onclick function
    turtle.clearscreen()
    end_screen()

    

opening_screen()
turtle.mainloop()
